### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by davclark** [msdse/org#1]
please put your email address below if you want to be added to the @msdse team

**Comment by stephuw** [comment]
stephuw

**Comment by epistemographer** [comment]
epistemographer (unless you want to whitelist sloan.org)

**Comment by karthik** [comment]
@epistemographer Added you (and also whitelisted Sloan)

**Comment by karthik** [comment]
@stephuw Is that at gmail? If not please tell me your full email.

**Comment by cmentzel** [comment]
err., moore.org

**Comment by karthik** [comment]
@cmentzel Moore is also whitelisted now.

**Comment by karthik** [comment]
@cmentzel Invited you manually (see email). I'll check on issues with the whitelist.

**Comment by hfrey** [comment]
Please add hfrey@ssl.berkeley.edu

**Comment by karthik** [comment]
@hfrey Invited.

**Comment by jakevdp** [comment]
Please add jakevdp@cs.washington.edu

**Comment by stephuw** [comment]
I'm already onboard here and on slack

**Comment by daagarwal** [comment]
please add daagarwal@lbl.gov or whitelist lbl.gov

**Comment by brittafiore** [comment]
please add sophia.sansone@gmail.com

**Comment by remram44** [comment]
Seems like my account is "disabled"? remi.rampin@nyu.edu

**Comment by davclark** [comment]
@remram44 - I'm not really managing the Slack anymore. I don't even get invited to the parties! The last time I did anything here, I made David Beck an owner, and he probably made others admins. @karthik is also an admin, I think. But anyway, this issue is not how the community is organizing right now...
